### ISSUE TITLE
Symbolic Computation Questions

### ISSUE THREAD

**Issue by brandonwillard** [RandallBalestriero/SymJAX#7]
I'm interested in hearing more about the computational graph manipulation.  Our project [`symbolic-pymc`](https://github.com/pymc-devs/symbolic-pymc) is exclusively about that, and a newer JAX-based tensor library with similarities to Theano sounds like a good thing to support.

To start, how exactly will SymJAX be similar to Theano with respect to symbolic graph manipulation?
More specifically,
* What's the general operator/arguments design in SymJAX's graph; will operator arguments generally map to high-level arguments (e.g. are parameters like `dtype` considered arguments at the same level as--say--the tensor inputs to a matrix multiplication)?  
* How much parity between user-level graph construction functions and their resulting classes/types do you plan on keeping (e.g. how easy will it be to map functions like `T.pdfs.multivariate_normal.pdf` to their resulting graphs and vice versa)?
* Are there any plans to support graph canonicalization?
* Are you planning on reproducing the entire Theano optimization system?

**Comment by RandallBalestriero** [comment]
Hello,
- there are a few arguments that can not be variable during the graph execution such as the shape and dtype, this is due to the fact that the graph to be compiled must have a priori fixed shapes and dtypes. This might be open for changes later on the Jax jit functionality, there are also a few details we are still working on regarding variable length of map functions
- if you mean to recover the underlying computational graph from a user defined function then yes this can be done easily by first getting the underlying Jax computation flow and then the corresponding jaxexpr
- for the graph canonicalization and Theano like optimization, we fully rely on the Jax underlying graph optimization and compilation system (see https://www.tensorflow.org/xla/ for details). We thus directly benefit from the optimized XLA compilation and produce a highly efficient user function with much faster compilation time that Theano. For more high level graph optimization, this is something we do consider but is not planned in a near future.
